/* Import data/dc_parks.csv */

-- mysql:

DROP TABLE IF EXISTS dc_parks;
CREATE TABLE `dc_parks` (
  `OBJECTID` INT(11) DEFAULT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  `ADDRESS` VARCHAR(255) DEFAULT NULL,
  `USE_TYPE` VARCHAR(255) DEFAULT NULL,
  `PROPID` VARCHAR(255) DEFAULT NULL,
  `ACTIVE` VARCHAR(255) DEFAULT NULL,
  `DIAMOND60` VARCHAR(255) DEFAULT NULL,
  `DIAMOND90` VARCHAR(255) DEFAULT NULL,
  `BBCOURT` VARCHAR(255) DEFAULT NULL,
  `FBFIELD` VARCHAR(255) DEFAULT NULL,
  `SOCCERJR` VARCHAR(255) DEFAULT NULL,
  `SOCCERREG` VARCHAR(255) DEFAULT NULL,
  `TENNISCT` VARCHAR(255) DEFAULT NULL,
  `VOLLEYB` VARCHAR(255) DEFAULT NULL,
  `SKATEPARK` VARCHAR(255) DEFAULT NULL,
  `WOODLAND` VARCHAR(255) DEFAULT NULL,
  `VSTRSHCAN` VARCHAR(255) DEFAULT NULL,
  `DMPSTR` VARCHAR(255) DEFAULT NULL,
  `PICNIC` VARCHAR(255) DEFAULT NULL,
  `PLYGRD` VARCHAR(255) DEFAULT NULL,
  `TOTLOT` VARCHAR(255) DEFAULT NULL,
  `INSWIM` VARCHAR(255) DEFAULT NULL,
  `OUTSWIM` VARCHAR(255) DEFAULT NULL,
  `SPRAYPARK` VARCHAR(255) DEFAULT NULL,
  `UTILBX` VARCHAR(255) DEFAULT NULL,
  `TRAFPOLE` VARCHAR(255) DEFAULT NULL,
  `UTILPOLE` VARCHAR(255) DEFAULT NULL,
  `BUSSTP` VARCHAR(255) DEFAULT NULL,
  `LOCK_` VARCHAR(255) DEFAULT NULL,
  `NMZ` VARCHAR(255) DEFAULT NULL,
  `DRINKFOUNT` VARCHAR(255) DEFAULT NULL,
  `BENCHES` VARCHAR(255) DEFAULT NULL,
  `ATHLIGHT` VARCHAR(255) DEFAULT NULL,
  `LNDSCPBED` VARCHAR(255) DEFAULT NULL,
  `TOTIMPV` VARCHAR(255) DEFAULT NULL,
  `SIGNS` VARCHAR(255) DEFAULT NULL,
  `TURFONLY` VARCHAR(255) DEFAULT NULL,
  `FENCE` VARCHAR(255) DEFAULT NULL,
  `TOPO` VARCHAR(255) DEFAULT NULL,
  `COMMGAR` VARCHAR(255) DEFAULT NULL,
  `WARD` VARCHAR(255) DEFAULT NULL,
  `AREA_` VARCHAR(255) DEFAULT NULL,
  `ZONE_` VARCHAR(255) DEFAULT NULL,
  `PARKPARTN` VARCHAR(255) DEFAULT NULL,
  `RES_NUM` VARCHAR(255) DEFAULT NULL,
  `ADJ_SCHOOL_SITE` VARCHAR(255) DEFAULT NULL,
  `SSL` VARCHAR(255) DEFAULT NULL,
  `COMMENTS` VARCHAR(255) DEFAULT NULL,
  `SHAPE_Length` VARCHAR(255) DEFAULT NULL,
  `SHAPE_Area` VARCHAR(255) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8; -- this table definition was copied from sequel pro's "table info" menu after the .csv file was first imported...

LOAD DATA LOCAL INFILE '~/projects/gwu-business/washington-dc-open-data/data/parks_2015.csv'
INTO TABLE dc_parks
FIELDS
  TERMINATED BY ','
  ENCLOSED BY '"'
LINES TERMINATED BY '\n' -- mac-style line breaks
  IGNORE 1 LINES
;

-- which column(s) can/should be the primary key?
SELECT
  `OBJECTID`
  ,count(*) AS row_count
FROM dc_parks
GROUP BY `OBJECTID`
HAVING row_count > 1; -- 0 rows (`OBJECTID` is a good pk candidate)

-- add indices ...

ALTER TABLE dc_parks ADD PRIMARY KEY(OBJECTID);

-- show end results ...

SELECT * FROM dc_parks;
